apiVersion: v1
kind: Secret
metadata:
  name: photoshare-secrets
  namespace: photoshare
type: Opaque
data:
  # Base64 encoded values
  # Use: echo -n "your_value" | base64
  supabase-service-key: "your_base64_encoded_service_key"